require('dotenv').config();
const express = require('express');
const multer  = require('multer');
const FormData = require('form-data');
const axios   = require('axios');
const fs      = require('fs');
const path    = require('path');
const {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, HeadingLevel, WidthType, AlignmentType, ShadingType,
  BorderStyle, Header, Footer
} = require('docx');

const app  = express();
const PORT = process.env.PORT || 3006;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

if (!OPENAI_API_KEY) {
  console.error('\n❌  OPENAI_API_KEY not set. Copy .env.example to .env and add your key.\n');
  process.exit(1);
}

// ── Dirs ────────────────────────────────────────────────────
const OUTPUT_DIR = path.join(__dirname, 'output');
const UPLOADS_DIR = path.join(__dirname, 'uploads');
[OUTPUT_DIR, UPLOADS_DIR].forEach(d => { if (!fs.existsSync(d)) fs.mkdirSync(d); });

// ── Static frontend ─────────────────────────────────────────
app.use(express.static(path.join(__dirname, 'public')));

// ── Multer (25 MB limit – Whisper API max) ───────────────────
const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, UPLOADS_DIR),
  filename:    (req, file, cb) => cb(null, `audio_${Date.now()}${path.extname(file.originalname) || '.webm'}`)
});
const upload = multer({
  storage,
  limits: { fileSize: 25 * 1024 * 1024 },
  fileFilter: (req, file, cb) => {
    const ok = /audio|video|octet-stream/.test(file.mimetype) ||
               /\.(mp3|mp4|m4a|wav|webm|ogg|mpeg|mpga|flac)$/i.test(file.originalname);
    cb(null, ok);
  }
});

// ── Helper: seconds → HH:MM:SS ──────────────────────────────
function fmt(sec) {
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  return [h, m, s].map(v => String(v).padStart(2, '0')).join(':');
}

// ── Helper: build Word document ──────────────────────────────
async function buildDocx(segments, meta) {
  const { filename, language, duration } = meta;
  const dateStr = new Date().toLocaleString('en-GB');

  // Header row style
  const hdrCell = (text) => new TableCell({
    shading: { type: ShadingType.SOLID, color: '2563EB' },
    borders: { top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE },
               left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } },
    children: [new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text, bold: true, color: 'FFFFFF', size: 20 })]
    })]
  });

  // Data row
  const dataCell = (text, align = AlignmentType.LEFT, bold = false) => new TableCell({
    borders: {
      top:    { style: BorderStyle.SINGLE, size: 1, color: 'E5E7EB' },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: 'E5E7EB' },
      left:   { style: BorderStyle.SINGLE, size: 1, color: 'E5E7EB' },
      right:  { style: BorderStyle.SINGLE, size: 1, color: 'E5E7EB' },
    },
    children: [new Paragraph({
      alignment: align,
      children: [new TextRun({ text: String(text), bold, size: 20 })]
    })]
  });

  const tableRows = [
    new TableRow({
      tableHeader: true,
      children: [
        hdrCell('Start'),
        hdrCell('End'),
        hdrCell('Transcript'),
      ]
    }),
    ...segments.map((seg, i) => new TableRow({
      children: [
        dataCell(fmt(seg.start), AlignmentType.CENTER, true),
        dataCell(fmt(seg.end),   AlignmentType.CENTER, true),
        dataCell(seg.text.trim()),
      ]
    }))
  ];

  const doc = new Document({
    creator: 'Hebrew/English Transcriber — benjyalper.com',
    title: `Transcription: ${filename}`,
    description: 'Auto-generated by Whisper AI',
    sections: [{
      children: [
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 100 },
          children: [new TextRun({ text: '🎙 Transcription', bold: true, size: 36, color: '1E3A8A' })]
        }),
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({ text: 'File: ',     bold: true, size: 20 }),
            new TextRun({ text: filename,              size: 20 }),
            new TextRun({ text: '   |   Date: ', bold: true, size: 20 }),
            new TextRun({ text: dateStr,               size: 20 }),
          ]
        }),
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({ text: 'Language: ', bold: true, size: 20 }),
            new TextRun({ text: language || 'Auto-detected', size: 20 }),
            new TextRun({ text: '   |   Duration: ', bold: true, size: 20 }),
            new TextRun({ text: fmt(duration || 0),           size: 20 }),
            new TextRun({ text: '   |   Segments: ', bold: true, size: 20 }),
            new TextRun({ text: String(segments.length),      size: 20 }),
          ]
        }),
        new Paragraph({
          spacing: { before: 200, after: 200 },
          border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: '2563EB' } },
          children: []
        }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          columnWidths: [1200, 1200, 7100],
          rows: tableRows
        }),
        new Paragraph({
          spacing: { before: 400 },
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: '— End of Transcription —', italics: true, color: '6B7280', size: 18 })]
        }),
      ]
    }]
  });

  return Packer.toBuffer(doc);
}

// ── POST /api/transcribe ─────────────────────────────────────
app.post('/api/transcribe', upload.single('audio'), async (req, res) => {
  const audioPath = req.file?.path;
  if (!audioPath) return res.status(400).json({ error: 'No audio file received.' });

  const language = req.body.language || 'auto'; // 'auto' | 'he' | 'en'

  try {
    console.log(`\n📎  Received: ${req.file.originalname} (${(req.file.size/1024).toFixed(1)} KB)`);
    console.log(`🌐  Language hint: ${language}`);

    // ── Call Whisper API ───────────────────────────────────
    const form = new FormData();
    form.append('file', fs.createReadStream(audioPath), {
      filename: req.file.originalname || 'audio.webm',
      contentType: req.file.mimetype || 'audio/webm',
    });
    form.append('model', 'whisper-1');
    form.append('response_format', 'verbose_json');
    form.append('timestamp_granularities[]', 'segment');
    if (language !== 'auto') form.append('language', language);

    console.log('🤖  Sending to Whisper…');
    const whisperRes = await axios.post(
      'https://api.openai.com/v1/audio/transcriptions',
      form,
      {
        headers: {
          ...form.getHeaders(),
          Authorization: `Bearer ${OPENAI_API_KEY}`,
        },
        maxContentLength: Infinity,
        maxBodyLength:    Infinity,
        timeout: 120_000,
      }
    );

    const data     = whisperRes.data;
    const segments = data.segments || [];
    const detectedLang = data.language || language;
    const duration = data.duration || (segments.length ? segments[segments.length-1].end : 0);

    console.log(`✅  Transcribed — ${segments.length} segments, lang: ${detectedLang}, duration: ${fmt(duration)}`);

    // ── Build docx ─────────────────────────────────────────
    const docBuffer = await buildDocx(segments, {
      filename: req.file.originalname || 'audio',
      language: detectedLang,
      duration,
    });

    const outName = `transcript_${Date.now()}.docx`;
    const outPath = path.join(OUTPUT_DIR, outName);
    fs.writeFileSync(outPath, docBuffer);
    console.log(`📄  Saved: output/${outName}`);

    // ── Clean up upload ────────────────────────────────────
    fs.unlinkSync(audioPath);

    res.json({
      ok: true,
      language: detectedLang,
      duration,
      segments,
      fullText: data.text,
      docFile: outName,
    });

  } catch (err) {
    if (audioPath && fs.existsSync(audioPath)) fs.unlinkSync(audioPath);
    console.error('❌ Transcription error:', err.response?.data || err.message);
    res.status(500).json({
      error: err.response?.data?.error?.message || err.message || 'Transcription failed'
    });
  }
});

// ── GET /api/download/:filename ──────────────────────────────
app.get('/api/download/:filename', (req, res) => {
  const safe = path.basename(req.params.filename);
  const filePath = path.join(OUTPUT_DIR, safe);
  if (!fs.existsSync(filePath)) return res.status(404).send('File not found');
  res.download(filePath, safe.replace(/^transcript_\d+/, 'Transcription'));
});

// ── Start ────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`\n🎙  Hebrew/English Transcriber running at http://localhost:${PORT}\n`);
});
